[Rule]
# Block UDP to force HTTP (Google QUIC)
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Script]
# 1. Request Script (Linked to YOUR GitHub)
youtube.request = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine=jsc,script-path=https://raw.githubusercontent.com/BigBossCoderTrader/YouTube_Premium_module/main/youtube.request.preview.js

# 2. Response Script (Linked to YOUR GitHub)
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine=jsc,script-path=https://raw.githubusercontent.com/BigBossCoderTrader/YouTube_Premium_module/main/youtube.response.preview.js,argument="{"lyricLang":"off","captionLang":"off","blockUpload":true,"blockImmersive":true,"debug":false}"

[Map Local]
# Remove initplayback ads
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data=""

[MITM]
hostname = *.googlevideo.com, youtubei.googleapis.com
